openapi: 3.0.0
info:
  title: "Mozilla IAM"
  description: IAM is a service to match authorization requests against predefined policies.
  version: "0.1"
  contact:
    url: "irc://irc.mozilla.org:6696/#product-delivery"
  license:
    name: "Mozilla Public License 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"

tags:
- name: Utilities
- name: Doorman

paths:
  /__heartbeat__:
    get:
      summary: "Is the server working properly? What is failing?"
      operationId: "heartbeat"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Server working properly"
          schema:
            type: "object"
        "503":
          description: "One or more subsystems failing."
          schema:
            type: "object"
      tags:
      - Utilities

  /__lbheartbeat__:
    get:
      summary: "Is the server reachable?"
      operationId: "lbheartbeat"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Server reachable"
          schema:
            type: "object"
      tags:
      - Utilities

  /__version__:
    get:
      summary: "Running instance version information"
      operationId: "version"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Return the running instance version information"
          schema:
            type: "object"
      tags:
      - Utilities

  /__api__:
    get:
      summary: "Open API Specification documentation."
      operationId: "doc"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Return the Open Api Specification."
          schema:
            type: "object"
      tags:
      - Utilities

  /contribute.json:
    get:
      summary: "Open source contributing information"
      operationId: "contribute"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Return open source contributing information."
          schema:
            type: "object"
      tags:
      - Utilities

  /allowed:
    post:
      summary: "Check if the specified request is allowed"
      operationId: "allowed"
      produces:
      - "application/json"
      requestBody:
        description: Authorization request
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                subject:
                  type: string
                action:
                  type: string
                resource:
                  type: string
                context:
                  type: object
      responses:
        "400":
          description: "Invalid posted data."
        "401":
          description: "Authentication failed."
        "200":
          description: "Return whether it is allowed or not."
          schema:
            type: object
            properties:
              allowed:
                type: boolean
      tags:
      - Doorman
